force-app/main/default/objects/Provider_Relations_Mass_Email__c/Provider_Relations_Mass_Email__c.object-meta.xml
<CustomObject>
    <label>Provider Relations Mass Email</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Provider Relations Mass Email #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Relations Mass Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider_Relations_Mass_Email__c/fields/Attachment_Names__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Names__c</fullName>
    <description>Names of all attachments sent with the Provider Email.</description>
    <label>Attachment Names</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Provider_Relations_Mass_Email__c/fields/Message_Plain_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Plain_Text__c</fullName>
    <label>Message Plain Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Provider_Relations_Mass_Email__c/fields/Message_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Rich_Text__c</fullName>
    <label>Message Rich Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/PrmsPaginatorEmail.cls
/**
 * Utilizes PrmsPaginatorFilterEmail and extends Paginator to assmeble query strings so Provider Relation Mass Email records can be delivered to Provider Relations Management Studio front end.
 * 
 * @see Paginator
 * @see PrmsPaginatorFilterEmail
 * 
 * @author Joel Comfort (March 2022)
 * @author Andrew Frederick (December 2022)
 */
public with sharing class PrmsPaginatorEmail extends Paginator {

    public PrmsPaginatorEmail( PrmsPaginatorFilterEmail filter ) {
        super(filter);
    }

    protected override String getSOQLString(){
        
        String q = 'SELECT ';
                q += 'Id, ';
                q += 'Message_Rich_Text__c, ';
                q += 'Message_Plain_Text__c, ';
                q += 'Attachment_Names__c, ';
                q += 'Subject__c, ';
                q += 'CreatedDate, ';
                q += 'CreatedBy.Name ';
                    q += 'FROM Provider_Relations_Mass_Email__c ';
                    q += filter.getFilterCriteria();

        return q;
    }

    protected override String getSOSLString(){

        String q = 'FIND \'' + filter.getSearch() +'\' IN ALL FIELDS ';
                q += 'RETURNING Provider_Relations_Mass_Email__c(';
                    q += 'Id, ';
                    q += 'Message_Rich_Text__c, ';
                    q += 'Message_Plain_Text__c, ';
                    q += 'Attachment_Names__c, ';
                    q += 'Subject__c, ';
                    q += 'CreatedDate, ';
                    q += 'CreatedBy.Name ';
                    q += filter.getFilterCriteria();
                q += ')';
        
        return q;
    }

    protected override String getSOQLCountString(){
        
        String q = 'SELECT ';
                q += 'count() ';
                    q += 'FROM Provider_Relations_Mass_Email__c ';
                    q += filter.getWhere();

        return q;
    }

    protected override String getSOSLCountString(){

        String q = 'FIND \'' + filter.getSearch() +'\' IN ALL FIELDS ';
                q += 'RETURNING Provider_Relations_Mass_Email__c(';
                    q += 'Id ';
                    q += filter.getWhere();
                q += ')';
        
        return q;
    }
}